require('sa.config.colors')
require('sa.config.tree')
require('sa.config.mason')
require('sa.config.lspsaga')
require('sa.config.treesitter')
require('sa.config.harpoon')
require('sa.config.lspconfig')
-- require('sa.config.completion')
-- require('sa.config.null')
